// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jraft.proto

package io.grpc.jraft;

/**
 * Protobuf type {@code jraft.AppendEntriesRequest}
 */
public  final class AppendEntriesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:jraft.AppendEntriesRequest)
    AppendEntriesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AppendEntriesRequest.newBuilder() to construct.
  private AppendEntriesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AppendEntriesRequest() {
    leaderId_ = "";
    entries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AppendEntriesRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            term_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            leaderId_ = s;
            break;
          }
          case 24: {

            prevLogIndex_ = input.readInt32();
            break;
          }
          case 32: {

            prevLogTerm_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000010) != 0)) {
              entries_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000010;
            }
            entries_.add(s);
            break;
          }
          case 48: {

            leaderCommit_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) != 0)) {
        entries_ = entries_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.jraft.JraftProto.internal_static_jraft_AppendEntriesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.jraft.JraftProto.internal_static_jraft_AppendEntriesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.jraft.AppendEntriesRequest.class, io.grpc.jraft.AppendEntriesRequest.Builder.class);
  }

  private int bitField0_;
  public static final int TERM_FIELD_NUMBER = 1;
  private int term_;
  /**
   * <code>int32 term = 1;</code>
   */
  public int getTerm() {
    return term_;
  }

  public static final int LEADERID_FIELD_NUMBER = 2;
  private volatile java.lang.Object leaderId_;
  /**
   * <code>string leaderId = 2;</code>
   */
  public java.lang.String getLeaderId() {
    java.lang.Object ref = leaderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      leaderId_ = s;
      return s;
    }
  }
  /**
   * <code>string leaderId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLeaderIdBytes() {
    java.lang.Object ref = leaderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      leaderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PREVLOGINDEX_FIELD_NUMBER = 3;
  private int prevLogIndex_;
  /**
   * <code>int32 prevLogIndex = 3;</code>
   */
  public int getPrevLogIndex() {
    return prevLogIndex_;
  }

  public static final int PREVLOGTERM_FIELD_NUMBER = 4;
  private int prevLogTerm_;
  /**
   * <code>int32 prevLogTerm = 4;</code>
   */
  public int getPrevLogTerm() {
    return prevLogTerm_;
  }

  public static final int ENTRIES_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList entries_;
  /**
   * <code>repeated string entries = 5;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getEntriesList() {
    return entries_;
  }
  /**
   * <code>repeated string entries = 5;</code>
   */
  public int getEntriesCount() {
    return entries_.size();
  }
  /**
   * <code>repeated string entries = 5;</code>
   */
  public java.lang.String getEntries(int index) {
    return entries_.get(index);
  }
  /**
   * <code>repeated string entries = 5;</code>
   */
  public com.google.protobuf.ByteString
      getEntriesBytes(int index) {
    return entries_.getByteString(index);
  }

  public static final int LEADERCOMMIT_FIELD_NUMBER = 6;
  private int leaderCommit_;
  /**
   * <code>int32 leaderCommit = 6;</code>
   */
  public int getLeaderCommit() {
    return leaderCommit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (term_ != 0) {
      output.writeInt32(1, term_);
    }
    if (!getLeaderIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, leaderId_);
    }
    if (prevLogIndex_ != 0) {
      output.writeInt32(3, prevLogIndex_);
    }
    if (prevLogTerm_ != 0) {
      output.writeInt32(4, prevLogTerm_);
    }
    for (int i = 0; i < entries_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, entries_.getRaw(i));
    }
    if (leaderCommit_ != 0) {
      output.writeInt32(6, leaderCommit_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (term_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, term_);
    }
    if (!getLeaderIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, leaderId_);
    }
    if (prevLogIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, prevLogIndex_);
    }
    if (prevLogTerm_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, prevLogTerm_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < entries_.size(); i++) {
        dataSize += computeStringSizeNoTag(entries_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getEntriesList().size();
    }
    if (leaderCommit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, leaderCommit_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.jraft.AppendEntriesRequest)) {
      return super.equals(obj);
    }
    io.grpc.jraft.AppendEntriesRequest other = (io.grpc.jraft.AppendEntriesRequest) obj;

    if (getTerm()
        != other.getTerm()) return false;
    if (!getLeaderId()
        .equals(other.getLeaderId())) return false;
    if (getPrevLogIndex()
        != other.getPrevLogIndex()) return false;
    if (getPrevLogTerm()
        != other.getPrevLogTerm()) return false;
    if (!getEntriesList()
        .equals(other.getEntriesList())) return false;
    if (getLeaderCommit()
        != other.getLeaderCommit()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + getTerm();
    hash = (37 * hash) + LEADERID_FIELD_NUMBER;
    hash = (53 * hash) + getLeaderId().hashCode();
    hash = (37 * hash) + PREVLOGINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getPrevLogIndex();
    hash = (37 * hash) + PREVLOGTERM_FIELD_NUMBER;
    hash = (53 * hash) + getPrevLogTerm();
    if (getEntriesCount() > 0) {
      hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getEntriesList().hashCode();
    }
    hash = (37 * hash) + LEADERCOMMIT_FIELD_NUMBER;
    hash = (53 * hash) + getLeaderCommit();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.jraft.AppendEntriesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.jraft.AppendEntriesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.jraft.AppendEntriesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.jraft.AppendEntriesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.jraft.AppendEntriesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.jraft.AppendEntriesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.jraft.AppendEntriesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.jraft.AppendEntriesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.jraft.AppendEntriesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.jraft.AppendEntriesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.jraft.AppendEntriesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.jraft.AppendEntriesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.jraft.AppendEntriesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code jraft.AppendEntriesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:jraft.AppendEntriesRequest)
      io.grpc.jraft.AppendEntriesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.jraft.JraftProto.internal_static_jraft_AppendEntriesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.jraft.JraftProto.internal_static_jraft_AppendEntriesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.jraft.AppendEntriesRequest.class, io.grpc.jraft.AppendEntriesRequest.Builder.class);
    }

    // Construct using io.grpc.jraft.AppendEntriesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      term_ = 0;

      leaderId_ = "";

      prevLogIndex_ = 0;

      prevLogTerm_ = 0;

      entries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      leaderCommit_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.jraft.JraftProto.internal_static_jraft_AppendEntriesRequest_descriptor;
    }

    @java.lang.Override
    public io.grpc.jraft.AppendEntriesRequest getDefaultInstanceForType() {
      return io.grpc.jraft.AppendEntriesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.grpc.jraft.AppendEntriesRequest build() {
      io.grpc.jraft.AppendEntriesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.grpc.jraft.AppendEntriesRequest buildPartial() {
      io.grpc.jraft.AppendEntriesRequest result = new io.grpc.jraft.AppendEntriesRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.term_ = term_;
      result.leaderId_ = leaderId_;
      result.prevLogIndex_ = prevLogIndex_;
      result.prevLogTerm_ = prevLogTerm_;
      if (((bitField0_ & 0x00000010) != 0)) {
        entries_ = entries_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.entries_ = entries_;
      result.leaderCommit_ = leaderCommit_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.jraft.AppendEntriesRequest) {
        return mergeFrom((io.grpc.jraft.AppendEntriesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.jraft.AppendEntriesRequest other) {
      if (other == io.grpc.jraft.AppendEntriesRequest.getDefaultInstance()) return this;
      if (other.getTerm() != 0) {
        setTerm(other.getTerm());
      }
      if (!other.getLeaderId().isEmpty()) {
        leaderId_ = other.leaderId_;
        onChanged();
      }
      if (other.getPrevLogIndex() != 0) {
        setPrevLogIndex(other.getPrevLogIndex());
      }
      if (other.getPrevLogTerm() != 0) {
        setPrevLogTerm(other.getPrevLogTerm());
      }
      if (!other.entries_.isEmpty()) {
        if (entries_.isEmpty()) {
          entries_ = other.entries_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureEntriesIsMutable();
          entries_.addAll(other.entries_);
        }
        onChanged();
      }
      if (other.getLeaderCommit() != 0) {
        setLeaderCommit(other.getLeaderCommit());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.jraft.AppendEntriesRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.jraft.AppendEntriesRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int term_ ;
    /**
     * <code>int32 term = 1;</code>
     */
    public int getTerm() {
      return term_;
    }
    /**
     * <code>int32 term = 1;</code>
     */
    public Builder setTerm(int value) {
      
      term_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 term = 1;</code>
     */
    public Builder clearTerm() {
      
      term_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object leaderId_ = "";
    /**
     * <code>string leaderId = 2;</code>
     */
    public java.lang.String getLeaderId() {
      java.lang.Object ref = leaderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leaderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string leaderId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLeaderIdBytes() {
      java.lang.Object ref = leaderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string leaderId = 2;</code>
     */
    public Builder setLeaderId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      leaderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string leaderId = 2;</code>
     */
    public Builder clearLeaderId() {
      
      leaderId_ = getDefaultInstance().getLeaderId();
      onChanged();
      return this;
    }
    /**
     * <code>string leaderId = 2;</code>
     */
    public Builder setLeaderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      leaderId_ = value;
      onChanged();
      return this;
    }

    private int prevLogIndex_ ;
    /**
     * <code>int32 prevLogIndex = 3;</code>
     */
    public int getPrevLogIndex() {
      return prevLogIndex_;
    }
    /**
     * <code>int32 prevLogIndex = 3;</code>
     */
    public Builder setPrevLogIndex(int value) {
      
      prevLogIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 prevLogIndex = 3;</code>
     */
    public Builder clearPrevLogIndex() {
      
      prevLogIndex_ = 0;
      onChanged();
      return this;
    }

    private int prevLogTerm_ ;
    /**
     * <code>int32 prevLogTerm = 4;</code>
     */
    public int getPrevLogTerm() {
      return prevLogTerm_;
    }
    /**
     * <code>int32 prevLogTerm = 4;</code>
     */
    public Builder setPrevLogTerm(int value) {
      
      prevLogTerm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 prevLogTerm = 4;</code>
     */
    public Builder clearPrevLogTerm() {
      
      prevLogTerm_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList entries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureEntriesIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        entries_ = new com.google.protobuf.LazyStringArrayList(entries_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <code>repeated string entries = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getEntriesList() {
      return entries_.getUnmodifiableView();
    }
    /**
     * <code>repeated string entries = 5;</code>
     */
    public int getEntriesCount() {
      return entries_.size();
    }
    /**
     * <code>repeated string entries = 5;</code>
     */
    public java.lang.String getEntries(int index) {
      return entries_.get(index);
    }
    /**
     * <code>repeated string entries = 5;</code>
     */
    public com.google.protobuf.ByteString
        getEntriesBytes(int index) {
      return entries_.getByteString(index);
    }
    /**
     * <code>repeated string entries = 5;</code>
     */
    public Builder setEntries(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEntriesIsMutable();
      entries_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string entries = 5;</code>
     */
    public Builder addEntries(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEntriesIsMutable();
      entries_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string entries = 5;</code>
     */
    public Builder addAllEntries(
        java.lang.Iterable<java.lang.String> values) {
      ensureEntriesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, entries_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string entries = 5;</code>
     */
    public Builder clearEntries() {
      entries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string entries = 5;</code>
     */
    public Builder addEntriesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureEntriesIsMutable();
      entries_.add(value);
      onChanged();
      return this;
    }

    private int leaderCommit_ ;
    /**
     * <code>int32 leaderCommit = 6;</code>
     */
    public int getLeaderCommit() {
      return leaderCommit_;
    }
    /**
     * <code>int32 leaderCommit = 6;</code>
     */
    public Builder setLeaderCommit(int value) {
      
      leaderCommit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 leaderCommit = 6;</code>
     */
    public Builder clearLeaderCommit() {
      
      leaderCommit_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:jraft.AppendEntriesRequest)
  }

  // @@protoc_insertion_point(class_scope:jraft.AppendEntriesRequest)
  private static final io.grpc.jraft.AppendEntriesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.jraft.AppendEntriesRequest();
  }

  public static io.grpc.jraft.AppendEntriesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppendEntriesRequest>
      PARSER = new com.google.protobuf.AbstractParser<AppendEntriesRequest>() {
    @java.lang.Override
    public AppendEntriesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AppendEntriesRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AppendEntriesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppendEntriesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.grpc.jraft.AppendEntriesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

