// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jraft.proto

package io.grpc.jraft;

public interface RequestVoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jraft.RequestVoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 term = 1;</code>
   */
  int getTerm();

  /**
   * <code>string candidateId = 2;</code>
   */
  java.lang.String getCandidateId();
  /**
   * <code>string candidateId = 2;</code>
   */
  com.google.protobuf.ByteString
      getCandidateIdBytes();

  /**
   * <code>int32 lastLogIndex = 3;</code>
   */
  int getLastLogIndex();

  /**
   * <code>int32 lastLogTerm = 4;</code>
   */
  int getLastLogTerm();
}
