// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jraft.proto

package io.grpc.jraft;

public interface RequestVoteReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jraft.RequestVoteReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 term = 1;</code>
   */
  int getTerm();

  /**
   * <code>bool voteGranted = 2;</code>
   */
  boolean getVoteGranted();
}
